language: python
python:
  - "3.5.2"
install:
  - pip install -r requirements.txt
  - pip install pylint
  - pip install mysqlclient
script:
  - python -m compileall ./red.py
  - python -m compileall ./cogs
  - python ./red.py --no-prompt --no-cogs --dry-run
  - pylint cogs/*
cache: pip
notifications:
  email: false
  webhooks:
    urls:
      - https://injabie3.moe/travis-ci-ren.php
    on_success: always # default: always
    on_failure: always # default: always
    on_start: always   # default: never
    on_cancel: always # default: always
    on_error: always # default: always
