# imports to make the dream

import random
import asyncio
import os
import discord
import time


''' dab '''
class dab:
  def __init__(self, bot):
    self.bot = bot
    
  @commands.command(name = "squid", pass_context = True)
	async def mycom(self):
	
    # generate a number
    number = print random.randint(0, 10000)
    
    # prints some ASCII art to whom ever is lucky enough
    if number = 666 or 420:
		
      await.self.bot.say("Squidward will visit you")
      await asyncio.sleep(5)
      await self.bot.say("\	                               `,;\*########+*:.")
      await asyncio.sleep(1)
      await self.bot.say("\	                           `,\*##+i::,,,,,:::;*##+,")
      await asyncio.sleep(1)
      await self.bot.say("\	                        `:+#+\**:,,,,,,,,,:**:,,,;+#;")
      await asyncio.sleep(1)
      await self.bot.say("\    	                  .\*#*:,+nni,,,,,,,,,;z#:,,,,,:*#.")
      await asyncio.sleep(1)
      await self.bot.say("\        	            :#+;,,,,\*#*:,,,,,,,,,,::,,,,,,,,:#;")
      await asyncio.sleep(1)
      await self.bot.say("\            	      ;#\*:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:+*")
      await asyncio.sleep(1)
      await self.bot.say("\                    :#\*:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,+*")
      await asyncio.sleep(1)
      await self.bot.say("\                  ,zn;,,,,,,,,,,,,,,,,,,:ii:,,,,,,,,,,,,,,,,+*")
      await asyncio.sleep(1)
      await self.bot.say("\                `*xnz;,,,,,,,,,,,,,,,,,:#nn+,,,,,,,,;i,,,,,,,+;")
      await asyncio.sleep(1)
      await self.bot.say("\               ,#i##;,,,,,:i*i:,,,,,,,,:+#+:,,,,,,,:zz;,,,,,,:z,")
      await asyncio.sleep(1)
      await self.bot.say("\             i#:,,,,,,,,:#nnz:,,,,,,,,,,:,,,,,,,,,:+*:,,,,,,,:z`")
      await asyncio.sleep(1)
      await self.bot.say("\            `#i,,,,,,,,,,;znzi,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,i*")
      await asyncio.sleep(1)
      await self.bot.say("\           .#;,,,,,,,,,,,,;;:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,#.")
      await asyncio.sleep(1)
      await self.bot.say("\         ,#:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;+")
      await asyncio.sleep(1)
      await self.bot.say("\        :#:,,,,::,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,ii")
      await asyncio.sleep(1)
      await self.bot.say("\       ,+,,,,,;#+,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:#")
      await asyncio.sleep(1)
      await self.bot.say("\      .n;,,,,:#n#,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,z`")
      await asyncio.sleep(1)
      await self.bot.say("\     `nn;,,,,;z#:,,,,,,,:;\*+#*:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,#,")
      await asyncio.sleep(1)
      await self.bot.say("\     +n#:,,,,,;:,,,,,,;+z#\*;::,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,*;")  
      await asyncio.sleep(1)
      await self.bot.say("\    :+i:,,,,,,,,,,,,;##;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;i                                                                             `;;:")
      await asyncio.sleep(1)
      await self.bot.say("\   `#:,,,,,,,,,,,,,+#;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;*                                                                          `:++;,i,")
      await asyncio.sleep(1)
      await self.bot.say("\  ii,,,,,,,,,,,,:z*,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:+                                                                    `.,;*+#*:,,,:*")
      await asyncio.sleep(1)
      await self.bot.say("\  `#,,,,,,,,,,,,;z;,,,,,,,,,,,:;ii,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:+                                                             .:;*++##+*i::,,,,,,,+")
      await asyncio.sleep(1)
      await self.bot.say("\  ii,,,,,,,,,,,:z:,,,,,,,,:i#zz#\*;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;*                                                        .;*##+*i:::,,,,,,,,,,,,,,+")
      await asyncio.sleep(1)
      await self.bot.say("\  #,,,,,,,,,,,:z;,,,,,,,;#z+;:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;*                                                     `i#+i:,,,,,,,,,,,,,,,,,,,,,:*")
      await asyncio.sleep(1)
      await self.bot.say("\ .+,,,,\**,,,,,+i,,,,,,:##;,,,,,,,,,,,,,,,,:::,,,,,,,,,,,,,,,,,,,,,ii                                                   `*#;:,,,,,,,,,,,,,,,,,,,,,,,:;;")
      await asyncio.sleep(1)
      await self.bot.say("\ i;,,,inz:,,,:#,,,,,,*z;,,,,,,,,,,,,,,:i#zz#i,,,,,,,,,,,,,,,,,,,,,+,                                                  .#;,,,,,,,,,,,,,,,,,,,,,,,,:;;#`")
      await asyncio.sleep(1)
      await self.bot.say("\ #:,,,#n#,,,,;;,,,,:#+,,,,,,,,,,,,:i#z#\*;:,,,,,,,,,,,,,,,,,,,,,,,,z`                                                 ,#:,,,,,,,,,,,,,,,,,,,,,,,,:;;**")
      await asyncio.sleep(1)
      await self.bot.say("\`#,,,:zz;,,,,,,,,,:zi,,,,,,,,,,,;+z+;:,,,,,,,,,,,,,,,,,,,,,,,,,,,:#                                                 ,#:,,,,,,,,,,,,,,,,,,,,,,,,:;;*z`")
      await asyncio.sleep(1)
      await self.bot.say("\:\*,,,,i;,,,,,,,,,:z;,,,,,,,,,,iz#;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,*;                                                `#:,,,,,,,,,,,,,,,,,,,,,,,:;;;zM,")
      await asyncio.sleep(1)
      await self.bot.say("\i;,,,,,,,,,,,,,,:z;,,,,,,,,,*z+:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,z`                                                +;,,,,,,,,,,,,,,,,,,,,,,,:;;;#Mi")
      await asyncio.sleep(1)
      await self.bot.say("\*:,,,,,,,,,,,,,,#i,,,,,,,,iz*:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;*                                                ;*,,,,,,,,,,,,,,,,,,,,,,:;;;;*Wi")
      await asyncio.sleep(1)
      await self.bot.say("\#*,,,,,,,,,,,,,i+,,,,,,,:##:,,,,,,,;+####+;,,,,,,,,,,,,,,,,,,,,,#.                                                #,,,,,,,,,,,,,,,,,,,,,:;ii;;;zi")
      await asyncio.sleep(1)
      await self.bot.say("\zz,,,,,,,,,,,,:#:,,,,,,iz;,,,,,,,:#+:,,,,;+#:,,,,,,,,,,,,,,,,,,i\*                                                ,*,,,,,,,,,,,,,,,,,,::;+nxx*;#;")
      await asyncio.sleep(1)
      await self.bot.say("\zz,,,,,,,,,,,,\*i,,,,,,*#:,,,,,,,,#;........:#*,,,,,,,,,,,,,,,,:z`                                               .z:,,,,,,,,,,,,,,::;;;inn##x*z:")
      await asyncio.sleep(1)
      await self.bot.say("\#\*,,,,,,,,,,,,*,,,,,,++,,,,,,,,,i*..........,++:,,,,,,,,,,,,,,+;                                               :#+,,,,,,,,,,,,,::;;;;;zz+#xn#`")
      await asyncio.sleep(1)
      await self.bot.say("\+;,,,,,,,,,,,,,,,,,,+\*,,,,,,,,,,#,............i#,,,,,,,,,,,,,;#                                              `**;:,,,,,,,,,,,,:;;;;;;;xnnxn;")
      await asyncio.sleep(1)
      await self.bot.say("\ii,,:i:,,,,,,,,,,,,+\*,,,,,,,,,,:z..............i+,,,,,,,,,,,:#.                                             ,#;,,,,,,,,,,,,,,;;;;;;;;;i*z*`")
      await asyncio.sleep(1)
      await self.bot.say("\:\*,,ini,,,,,,,,,,,i+,,,,,,,,,,,;#...............**,,,,,,,,,,*i                                            `*+:,,,,,,,,,,,,,,;;;;;*#z#*#+.")
      await asyncio.sleep(1)
      await self.bot.say("\.#,,+n*,,,,,,,,,,:z:,,,,,,,,,,,;#................#;,,,,,,,,;#                                            ,#i,,,,,,,,,,,,,,,:;;;inn#zx#,")
      await asyncio.sleep(1)
      await self.bot.say("\`#,,+ni,,,,,,,,,,#;,,,,,,,,,,,,:#................,z:,,,,,,iz.                                          `*+:,,,,,,,,,,,,,,,,:;;;nzzn+.")
      await asyncio.sleep(1)
      await self.bot.say("\ #:,;i:,,,,,,,,,;#,,,,,,,::::,,,#.................i\*,,,,,,**                                          ,#i,,,,,,,,,,,,,:::,,:;;+Mzi`")
      await asyncio.sleep(1)
      await self.bot.say("\ii,,,,,,,,,,,,,#:,,,,,;##++##i:#,......,:.........#:,,,,,:#                                        `*+:,,,,,,,,,,,,,;####++++;.")
      await asyncio.sleep(1)
      await self.bot.say("\.#,,,,,,,,,,,,:#,,,,,\*#,....,*z#i.....*nx;........;+,,,,,,*;   `:i++++i.                          :#;,,,,,,,,,,,,,;#*.")
      await asyncio.sleep(1)
      await self.bot.say("\#:,,,,,,,,,,,i*,,,,;#,.......,+n....,nxxz,.......,z:,,,,,,+.i++i;:,,,;++\`                      `++:,,,,,,,,,,,,i#i`")
      await asyncio.sleep(1)
      await self.bot.say("\ ;*,,,,,,,,,,,+;,,,,#:..........#;....zxxx;........ii,,,,,:##;,,,,,,,,,,;#\`                    ;#;,,,,,,,,,,,,i#i`")
      await asyncio.sleep(1)
      await self.bot.say("\ \`#,,,,,,,,,,,::,,,:z...........:#....ixxxn,.......,#,,,,iz;,,,,,,,,,,,,,:#`                 .+*,,,,,,,,,,,,i#i`")
      await asyncio.sleep(1)
      await self.bot.say("\  ii,,,,,,,,,,,,,,,:+............+:...,xxxx#........#:,,:i,,,,,,,,,,:::,,,i;                ;+:,,,,,,,,,,:i#;`")
      await asyncio.sleep(1)
      await self.bot.say("\  \`#:,,,,,,,,,,,,,,:+............,#....*xxxxi.......+;,,,,,,,,,,:i#####z#ii;              .+i,,,,,,,,,,,i#i`")
      await asyncio.sleep(1)
      await self.bot.say("\   :+,,,,,,,,,,,,,,:+.............\*i...,zxxxxi......ii,,,,,,,,;##*:,,,,,:*n#,\`           i+:,,,,,,,,,,izi`")
      await asyncio.sleep(1)
      await self.bot.say("\    +i,,,,,,,,,,,,,:#.............,#,...:nxxxx;.....ii,,,,,,:##;,,,,,,,,,,:;+##\*;.\`    .#i,,,,,,,,,,i#*`")
      await asyncio.sleep(1)
      await self.bot.say("\     \`#;,,,,,,,,,,,,,z......:;,.....;+....;xxxxx:....+;,,,,,iz;,,,,,,,,,,,,,,,,::i+##*;i#:,,,,,,,,,;#i`")
      await asyncio.sleep(1)
      await self.bot.say("\      \`#;,,,,,,,,,,,,#:....*xxi......+i....;nxxx:...,z,,,,:#+:,,,,,,,,,,,,,,,,,,,,,,,:i+z;,,,,,,,;#*`")
      await asyncio.sleep(1)
      await self.bot.say("\      \`+\*:,,,,,,,,,,i*...,xxxx:.....,#i....:zx*....i*,,,:zi,,,,,,,,,,,,,,,,,,,,,,,,,,,,:z,,,,,;#*`")
      await asyncio.sleep(1)
      await self.bot.say("\         ;#i,,,,,,,,,:z....#xxxz,....ii#\*....,:....:z:,,;z;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,#,,,;#*`")
      await asyncio.sleep(1)
      await self.bot.say("\          \`i#+i;:::;iiz;...:nxxx+....#:,\*#:.......:z:,,*#:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:z,;#*`")
      await asyncio.sleep(1)
      await self.bot.say("\             .;\*++*i;:,#,...*xxxx*..,#,,,:##i,.,:+#:,,++:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,#*#*`")
      await asyncio.sleep(1)
      await self.bot.say("\                       ;\*...,zxxxx*.:+,,,,,:*#nz+;,,:#*,,,,,,,,,:::;::::::::,,,,,,,,::;zM*`")
      await asyncio.sleep(1)
      await self.bot.say("\                        +:...:nxxxx#ii,,,,,,,,i\*,,,:z;,,,,,,,,:;;;;;;;;i**i;;;;;;;;;;in+.")
      await asyncio.sleep(1)
      await self.bot.say("\                        `#,...;nxxxxx;,,,,,,,,,z;,;z;,,,,,,,,;;;;;;;;;zxnxxni;;;i#nz##,")
      await asyncio.sleep(1)
      await self.bot.say("\                         .#,...:nxxxM:,,,,,,,,,:z\*z:,,,,,,;+;;;iii;;;*n##++z+;;ixznz,")
      await asyncio.sleep(1)
      await self.bot.say("\                          ,#,...,#xnx:,,,,,,,,,,\*z:,,,,,,:z,z*znnnni;*x###nxi;;zxz;")
      await asyncio.sleep(1)
      await self.bot.say("\                           .#:....;,#:,,,,,,,,,\*+,,,,,,,:#, `*x##+#xi;*zzz+ii+nx,")
      await asyncio.sleep(1)
      await self.bot.say("\   		                     `+\*,....z:,,,,,,,,++,,,,,,,,+:    ,xMnnM+++++#znnz#n:")
      await asyncio.sleep(1)
      await self.bot.say("\                             ,zz#++#x:,,,,,,:#\*,,,,,,,,*nn+` ;xz##zzznzzz#######i")
      await asyncio.sleep(1)
      await self.bot.say("\                            :#:,:;;:z:,,,,,:#i,,,,,,,,in##zn#n##################*")
      await asyncio.sleep(1)
      await self.bot.say("\                           .#:,,,,,,z:,,,,:zi,,,,,,,,;xx####Mz#################zi")
      await asyncio.sleep(1)
      await self.bot.say("\                          `#:,,,,,,,+;,,,:z;,,,,,,,,:z:*x####M#################n:")
      await asyncio.sleep(1)
      await self.bot.say("\                          ii,,,,,,,,\**,,:z;,,,,,,,,:z;,,;n###zx##############n#.")
      await asyncio.sleep(1)
      await self.bot.say("\                         `#,,,,,,,,;##,:z;,,,,,,,,,#i,,,,:n###x############zn:")
      await asyncio.sleep(1)
      await self.bot.say("\                         :\*,,,,,,:+#:z:z;,,,,,,,,,+*,,,,,,;n##zn#########nn;`")
      await asyncio.sleep(1)
      await self.bot.say("\                         +:,,,,,:#i,,#z:,,,,,,,,,i+,,,,,,,,z###x#######nz;`")
      await asyncio.sleep(1)
      await self.bot.say("\                         #,,,,,:z;,,:z;,,,,,,,,,;#:,,,,,,,,;Mn#x###n#nz:")
      await asyncio.sleep(1)
      await self.bot.say("\                        `#,,,,:z:,,:z;,,,,,,,,,:z:,,,,,,,,,,nzxM####M+")
      await asyncio.sleep(1)
      await self.bot.say("\                       `#,,,,#;,,:z;,,,,,,,,,,#;,,,,,,,,,,,z##n#####ni")
      await asyncio.sleep(1)
      await self.bot.say("\                       `#,,,i\*,,,#;,,,,,,,,,,**,,,,,,,,,,,,+#########ni")
      await asyncio.sleep(1)
      await self.bot.say("\                        #,,,:,,,+i,,,,,,,,,,;#,,,,,,,,,,,,,+##########n:")
      await asyncio.sleep(1)
      await self.bot.say("\                        \*:,,,,,**,,,,,,,,,,:#:,,,,,,,,,,,,,############n.")
      await asyncio.sleep(1)
      await self.bot.say("\                        ,+,,,,;#,,,,,,,,,,,+i,,,,,,,,,,,,,,n#############")
      await asyncio.sleep(1)
      await self.bot.say("\                         i#i;iz:,,,,,,,,,,;#,,,,,,,,,,,,,,;n############n:")
      await asyncio.sleep(1)
      await self.bot.say("\                          .;\*ni,,,,,,,,,,:#:,,,,,,,,,,,,,,z##############n`")
      await asyncio.sleep(1)
      await self.bot.say("\                            .+,,,,,,,,,,,\**,,,,,,,,,,,,,,*n##############z*")
      await asyncio.sleep(1)
      await self.bot.say("\	                        +:,,,,,,,,,,:nz:,,,,,,,,,,,,+n################n.")
      await asyncio.sleep(1)
      await self.bot.say("\                           .+,,,,,,,,,,,##zz;,,,,,,,,,;zn##################+")
      await asyncio.sleep(1)
      await self.bot.say("\                           *:,,,,,,,,,,;x###nz+;::::i#xz###################n,")
      await asyncio.sleep(1)
      await self.bot.say("\                          `+,,,,,,,,,,:z######znnnxn;.,z####################+")
      await asyncio.sleep(1)
      await self.bot.say("\                          :i,,,,,,,,,:#z########zni`   #####################x,")
      await asyncio.sleep(1)
      await self.bot.say("\                          *:,,,,,,,,,+n########n+`     :n####################+")
      await asyncio.sleep(1)
      await self.bot.say("\                          +:,,,,,,,:+n#######nz,       \`n####################n`")
      await asyncio.sleep(1)
      await self.bot.say("\                          zz:,,,,,inz######nz:          #####################z;")
      await asyncio.sleep(1)
      await self.bot.say("\                          znn+ii+nn#####zn#,            i######################")
      await asyncio.sleep(1)
      await self.bot.say("\                          ,zzznnz####znz*.              :z####################n`")
      await asyncio.sleep(1)
      await self.bot.say("\                           `*znnnnnz+;.                 ,n####################n:")
      await asyncio.sleep(1)
      await self.bot.say("\                              ....                      .n#####################*")
      await asyncio.sleep(1)
      await self.bot.say("\                                                       .n#####################z")
      await asyncio.sleep(1)
      await self.bot.say("\                                                       .n#####################n`")
      await asyncio.sleep(1)
      await self.bot.say("\                                                        :z#####################n,")
      await asyncio.sleep(1)
      await self.bot.say("\                                                        *z#####################z;")
      await asyncio.sleep(1)
      await self.bot.say("\                                                        ########################+")
      await asyncio.sleep(1)
      await self.bot.say("\                                                       `n#######################z")
      await asyncio.sleep(1)
      await self.bot.say("\                                                       ,n#######################n")
      await asyncio.sleep(1)
      await self.bot.say("\                                                        *########################n`")
      await asyncio.sleep(1)
      await self.bot.say("\                                                        n########################x,")
      await asyncio.sleep(1)
      await self.bot.say("\                                                       ,n########################n,")
      await asyncio.sleep(1)
      await self.bot.say("\                                                       +#########################n:")
      await asyncio.sleep(1)
      await self.bot.say("\                                                      `n#########################z;")
      await asyncio.sleep(1)
      await self.bot.say("\                                                      ;z########znxxxxxxnzz######z;")
      await asyncio.sleep(1)
      await self.bot.say("\                                                      z######nnz+i;:::::;*#nxz###z:")
      await asyncio.sleep(1)
      await self.bot.say("\                                                     ,n###zxz;:,,,,,,,,,,,,,:*nn#n,")
      await asyncio.sleep(1)
      await self.bot.say("\                                                     ,n#zx#:,,,,,,,,,,,,,,,,,,:*nn`")
      await asyncio.sleep(1)
      await self.bot.say("\                                                     znz;,,,,,,,,,,,,,,,,,,,,,,;+")
      await asyncio.sleep(1)
      await self.bot.say("\                                                      .#,,,,,,,,,,,,,,,,,,,,,,,,+:")
      await asyncio.sleep(1)
      await self.bot.say("\                                                      .*,,,,,,,,,,,,,,,,,,,,,,,,+.")
      await asyncio.sleep(1)
      await self.bot.say("\                                                      i;,,,,,,,,,,,,,,,,,,,,,,,,#")
      await asyncio.sleep(1)
      await self.bot.say("\                                                     `#,,,,,,,,,,,,,,,,,,,,,,,,:+")
      await asyncio.sleep(1)
      await self.bot.say("\                                                     ;i,,,,,,,,,,,,,,,,,,,,,,,,i:")
      await asyncio.sleep(1)
      await self.bot.say("\                                                     #:,,,,,,,,,,,,,,,,,,,,,,,:z`")
      await asyncio.sleep(1)
      await self.bot.say("\                                                    ,+,,,,,,,,,,,,,,,,,,,,,,,,z;")
      await asyncio.sleep(1)
      await self.bot.say("\                                                    +:,,,,,,,,,,,,,,,,,,,,,,:#n`")
      await asyncio.sleep(1)
      await self.bot.say("\                                                   .#,,,,:i,,,,,,,,,,,,,,,,:#i#")
      await asyncio.sleep(1)
      await self.bot.say("\                                                   \*;,,,,*ni,,,,,,,,i:,,,;iz;,#")
      await asyncio.sleep(1)
      await self.bot.say("\                                                  `#,,,,:z:+#i:,,,,,#:,,,#*:,,+")
      await asyncio.sleep(1)
      await self.bot.say("\                                                  i;,,,,\**,,:+##z##*z,,,,#:,,,+")
      await asyncio.sleep(1)
      await self.bot.say("\                                                 \`+,,,,:z,,,,,,,#. `#,,,,#:,,,+")
      await asyncio.sleep(1)
      await self.bot.say("\                                                 :;,,,,\*i,,,,,,ii  ,*,,,,+:,,,:")
      await asyncio.sleep(1)
      await self.bot.say("\                                                 .\`\`\`\`\`:\`\`\`\`\`\`\`.   \`.\`\`\` '")
      await asyncio.sleep(5)
      await.self.bot.say("Squidward has visited you")
      break
      
      # for the unlucky ones
    else:
      await.self.bot.say("He won't visit you yet")
      await.self.bot.say("maybe if you're lucky you'll get to see him")
      break
      
      
